name: CI
on: push
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: install packages
        run: npm install

      - name: Build
        run: npm run build
        run: npm run export

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.TOKEN }}
          external_repository: pradow/pokefetch
          publish_dir: ./out
          user_name: pradow
          user_email: pradochris+pradow@protonmail.com
          publish_branch: gh-pages
